//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.11.2
//     from Assets/InputActions/Swipe.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @Swipe: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @Swipe()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""Swipe"",
    ""maps"": [
        {
            ""name"": ""Touch"",
            ""id"": ""4c4e4b02-21df-42be-a23f-23fee1dfa727"",
            ""actions"": [
                {
                    ""name"": ""TouchDetection"",
                    ""type"": ""PassThrough"",
                    ""id"": ""258151e4-eff3-40f7-9f67-de43cede2ef8"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SwipeGesture"",
                    ""type"": ""PassThrough"",
                    ""id"": ""2489089a-1d83-4090-b06e-e75b84c6ff04"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""e76b5a7b-43d9-4cd0-be5b-8c1968cd6230"",
                    ""path"": ""<Touchscreen>/primaryTouch/press"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TouchDetection"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""09312171-481a-4da7-bbba-d2394457189d"",
                    ""path"": ""<Touchscreen>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SwipeGesture"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Touch
        m_Touch = asset.FindActionMap("Touch", throwIfNotFound: true);
        m_Touch_TouchDetection = m_Touch.FindAction("TouchDetection", throwIfNotFound: true);
        m_Touch_SwipeGesture = m_Touch.FindAction("SwipeGesture", throwIfNotFound: true);
    }

    ~@Swipe()
    {
        UnityEngine.Debug.Assert(!m_Touch.enabled, "This will cause a leak and performance issues, Swipe.Touch.Disable() has not been called.");
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Touch
    private readonly InputActionMap m_Touch;
    private List<ITouchActions> m_TouchActionsCallbackInterfaces = new List<ITouchActions>();
    private readonly InputAction m_Touch_TouchDetection;
    private readonly InputAction m_Touch_SwipeGesture;
    public struct TouchActions
    {
        private @Swipe m_Wrapper;
        public TouchActions(@Swipe wrapper) { m_Wrapper = wrapper; }
        public InputAction @TouchDetection => m_Wrapper.m_Touch_TouchDetection;
        public InputAction @SwipeGesture => m_Wrapper.m_Touch_SwipeGesture;
        public InputActionMap Get() { return m_Wrapper.m_Touch; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(TouchActions set) { return set.Get(); }
        public void AddCallbacks(ITouchActions instance)
        {
            if (instance == null || m_Wrapper.m_TouchActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_TouchActionsCallbackInterfaces.Add(instance);
            @TouchDetection.started += instance.OnTouchDetection;
            @TouchDetection.performed += instance.OnTouchDetection;
            @TouchDetection.canceled += instance.OnTouchDetection;
            @SwipeGesture.started += instance.OnSwipeGesture;
            @SwipeGesture.performed += instance.OnSwipeGesture;
            @SwipeGesture.canceled += instance.OnSwipeGesture;
        }

        private void UnregisterCallbacks(ITouchActions instance)
        {
            @TouchDetection.started -= instance.OnTouchDetection;
            @TouchDetection.performed -= instance.OnTouchDetection;
            @TouchDetection.canceled -= instance.OnTouchDetection;
            @SwipeGesture.started -= instance.OnSwipeGesture;
            @SwipeGesture.performed -= instance.OnSwipeGesture;
            @SwipeGesture.canceled -= instance.OnSwipeGesture;
        }

        public void RemoveCallbacks(ITouchActions instance)
        {
            if (m_Wrapper.m_TouchActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(ITouchActions instance)
        {
            foreach (var item in m_Wrapper.m_TouchActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_TouchActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public TouchActions @Touch => new TouchActions(this);
    public interface ITouchActions
    {
        void OnTouchDetection(InputAction.CallbackContext context);
        void OnSwipeGesture(InputAction.CallbackContext context);
    }
}
